// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt67UOpTFpCNgndjjW0JH_EU1llJOKRes',
    appId: '1:880350310387:web:d2157c87d30d5d295e6c86',
    messagingSenderId: '880350310387',
    projectId: 'ecommerceapp-54fed',
    authDomain: 'ecommerceapp-54fed.firebaseapp.com',
    storageBucket: 'ecommerceapp-54fed.appspot.com',
    measurementId: 'G-J8V353DGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfXqdG56LVbi_ksKBvpyE3CmsBuj1CRY',
    appId: '1:880350310387:android:c38eb01eb41756b65e6c86',
    messagingSenderId: '880350310387',
    projectId: 'ecommerceapp-54fed',
    storageBucket: 'ecommerceapp-54fed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWLSSfgAUbIdwL1NLeDmX8_SyiaTTBRdg',
    appId: '1:880350310387:ios:b80914a8267392805e6c86',
    messagingSenderId: '880350310387',
    projectId: 'ecommerceapp-54fed',
    storageBucket: 'ecommerceapp-54fed.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWLSSfgAUbIdwL1NLeDmX8_SyiaTTBRdg',
    appId: '1:880350310387:ios:b80914a8267392805e6c86',
    messagingSenderId: '880350310387',
    projectId: 'ecommerceapp-54fed',
    storageBucket: 'ecommerceapp-54fed.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt67UOpTFpCNgndjjW0JH_EU1llJOKRes',
    appId: '1:880350310387:web:b6daa66eebc7c2565e6c86',
    messagingSenderId: '880350310387',
    projectId: 'ecommerceapp-54fed',
    authDomain: 'ecommerceapp-54fed.firebaseapp.com',
    storageBucket: 'ecommerceapp-54fed.appspot.com',
    measurementId: 'G-DDLX9FW4E0',
  );
}
